# Generated by Django 2.1.7 on 2019-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='off_hour',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='on_hour',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
