# Generated by Django 2.1.7 on 2019-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerdetail',
            name='add_lat',
        ),
        migrations.RemoveField(
            model_name='dealerdetail',
            name='add_lon',
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='has_bike',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
