# Generated by Django 2.1.7 on 2019-04-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190406_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
