# Generated by Django 2.1.7 on 2019-03-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_dealerdetail_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerdetail',
            name='avatar',
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='media'),
        ),
    ]
