# Generated by Django 2.1.7 on 2019-04-11 04:29

import Users.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190406_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default='def.jpeg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
