# Generated by Django 2.1.7 on 2019-03-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190316_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='media'),
        ),
    ]
