# Generated by Django 2.1.7 on 2019-03-17 08:24

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_clientdetail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default=None, upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='image',
            field=models.ImageField(default=None, upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
    ]
