# Generated by Django 2.1.7 on 2019-04-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerdetail',
            name='add_1',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='add_2',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='area',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dealerdetail',
            name='city',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
