# Generated by Django 2.1.7 on 2019-03-17 10:26

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20190317_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default='/media/def.jpeg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/defthumb.jpeg', upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
    ]
