# Generated by Django 2.2 on 2021-09-11 10:51

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20190417_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defthumb.jpg', upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defthumb.jpg', upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
    ]
