# Generated by Django 2.1.7 on 2019-03-17 12:39

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_auto_20190317_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default='def.jpg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defthumb.jpg', upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
    ]
