# Generated by Django 2.1.7 on 2019-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_auto_20190317_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
