# Generated by Django 2.1.7 on 2019-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_customuser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(default='0000000000', max_length=12),
        ),
    ]
