# Generated by Django 2.1.7 on 2019-03-23 10:02

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_auto_20190323_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='image',
            field=models.ImageField(default='def.jpeg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defthumb.jpeg', upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='image',
            field=models.ImageField(default='def.jpeg', upload_to=Users.models.scramble_uploaded_filename, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='dealerdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defthumb.jpeg', upload_to='', verbose_name='Thumbnail of uploaded image'),
        ),
    ]
