# Generated by Django 2.1.7 on 2019-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrxnDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.CharField(max_length=20)),
                ('ORDER_ID', models.CharField(max_length=50)),
                ('CUST_ID', models.CharField(max_length=64)),
                ('TXN_AMOUNT', models.CharField(max_length=10)),
                ('CHANNEL_ID', models.CharField(max_length=3)),
                ('WEBSITE', models.CharField(max_length=30)),
                ('INDUSTRY_TYPE_ID', models.CharField(max_length=20)),
                ('CHECKSUMHASH', models.CharField(max_length=108)),
                ('MOBILE_NO', models.CharField(max_length=15)),
                ('EMAIL', models.CharField(max_length=50)),
            ],
        ),
    ]
