# Generated by Django 2.1.7 on 2019-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_remove_trxndetail_checksumhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxndetail',
            name='CALLBACK_URL',
            field=models.CharField(max_length=108, null=True),
        ),
    ]
