# Generated by Django 2.1.7 on 2019-04-06 05:49

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(default='type..', max_length=500)),
                ('image', models.ImageField(default='def.jpg', upload_to=api.models.scramble_uploaded_filename, verbose_name='media')),
                ('thumbnail', models.ImageField(blank=True, default='defthumb.jpg', upload_to='', verbose_name='Thumbnail of uploaded image')),
            ],
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='type..', max_length=500)),
                ('count', models.IntegerField(default=0)),
                ('bike_rate_hr', models.CharField(blank=True, max_length=500, null=True)),
                ('bike_rate_h', models.CharField(blank=True, max_length=500, null=True)),
                ('bike_rate_f', models.CharField(blank=True, max_length=500, null=True)),
                ('bike_isAvailable', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('bike_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Bike')),
                ('dealer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.DealerDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(default=None)),
                ('dob', models.DateTimeField(default=None)),
                ('duration', models.CharField(default=0.0, max_length=500)),
                ('transaction_amt', models.CharField(default=0.0, max_length=500)),
                ('ord_id', models.CharField(default=0.0, max_length=500)),
                ('transaction_id', models.CharField(default=0.0, max_length=500)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_Booked', models.BooleanField(default=False)),
                ('bike_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.BikeModel')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.ClientDetail')),
                ('dealer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.DealerDetail')),
            ],
        ),
    ]
