# Generated by Django 2.1.7 on 2019-02-28 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.CharField(max_length=25, unique=True)),
                ('bike_img', models.CharField(max_length=500)),
                ('bike_rate_hr', models.CharField(max_length=500, null=True)),
                ('bike_rate_h', models.CharField(max_length=500, null=True)),
                ('bike_rate_f', models.CharField(max_length=500, null=True)),
                ('bike_isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_model', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=0)),
                ('icon_img', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_from', models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 13, 47, 751362, tzinfo=utc))),
                ('bike_till', models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 13, 47, 751362, tzinfo=utc))),
                ('transaction', models.CharField(default=0.0, max_length=500)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bike')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.ClientDetail')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.BikeModel'),
        ),
        migrations.AddField(
            model_name='bike',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.DealerDetail'),
        ),
    ]
