# Generated by Django 2.1.7 on 2019-02-28 13:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_rate_f',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_rate_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_rate_hr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 24, 47, 704527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 24, 47, 704527, tzinfo=utc)),
        ),
    ]
