# Generated by Django 2.1.7 on 2019-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
