# Generated by Django 2.1.7 on 2019-02-28 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190228_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 25, 23, 326248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 25, 23, 326248, tzinfo=utc)),
        ),
    ]
