# Generated by Django 2.1.7 on 2019-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190406_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_Booked',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('cancelled', 'cancelled'), ('booked', 'booked'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
