# Generated by Django 2.1.7 on 2019-02-28 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190228_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bike_rate_f',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_rate_h',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_rate_hr',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 26, 28, 188326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 26, 28, 188326, tzinfo=utc)),
        ),
    ]
