# Generated by Django 2.1.7 on 2019-02-28 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190228_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_rate_f',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_rate_h',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_rate_hr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 32, 35, 607471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 32, 35, 607471, tzinfo=utc)),
        ),
    ]
