# Generated by Django 2.1.7 on 2019-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190406_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='dob',
            new_name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_unit',
            field=models.CharField(choices=[('hrs', 'hrs'), ('half_day', 'half_day'), ('full_day', 'full_day')], default='hrs', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('failed', 'failed'), ('booked', 'booked'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
