# Generated by Django 2.1.7 on 2019-02-28 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('api', '0006_auto_20190228_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='dealer',
            field=models.ManyToManyField(to='Users.DealerDetail'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 15, 7, 8, 793681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 15, 7, 8, 793681, tzinfo=utc)),
        ),
    ]
