# Generated by Django 2.1.7 on 2019-02-28 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190228_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='dealer',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 15, 43, 20, 664294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 15, 43, 20, 664294, tzinfo=utc)),
        ),
    ]
