# Generated by Django 2.1.7 on 2019-03-03 13:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190303_1850'),
        ('api', '0010_auto_20190228_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bike_img',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_isAvailable',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_model',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_number',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_rate_f',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_rate_h',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='bike_rate_hr',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='bikemodel',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='bikemodel',
            name='icon_img',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bike',
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_name',
            field=models.CharField(default='type..', max_length=500),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='bike_img',
            field=models.CharField(default='type..', max_length=500),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='bike_isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='bike_rate_f',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='bike_rate_h',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='bike_rate_hr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='dealer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.DealerDetail'),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='description',
            field=models.CharField(default='type..', max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='bike_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.BikeModel'),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='bike_model',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.Bike'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 13, 20, 56, 642696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 13, 20, 56, 642696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.ClientDetail'),
        ),
    ]
