# Generated by Django 2.1.7 on 2019-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190303_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bike_from',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike_till',
            field=models.DateTimeField(default=None),
        ),
    ]
