# Generated by Django 2.1.7 on 2019-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190303_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='bike_rate_f',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='bike_rate_h',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='bike_rate_hr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
