# Generated by Django 2.1.7 on 2019-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190303_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='avatar',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='bikemodel',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
