# Generated by Django 2.1.7 on 2019-03-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190317_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikemodel',
            name='bike_img',
        ),
        migrations.RemoveField(
            model_name='bikemodel',
            name='thumbnail',
        ),
    ]
