# Generated by Django 2.1.7 on 2019-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190320_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bike_till',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(default=0.0, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ord_id',
            field=models.CharField(default=0.0, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(default=0.0, max_length=500),
        ),
    ]
