# Generated by Django 2.1.7 on 2019-03-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190323_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='transaction',
            new_name='transaction_amt',
        ),
    ]
