# Generated by Django 2.1.7 on 2019-03-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_auto_20190323_1002'),
        ('api', '0018_auto_20190328_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dealer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.DealerDetail'),
        ),
    ]
