# Generated by Django 2.1.7 on 2019-03-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_booking_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dealer',
        ),
    ]
